Fix variable scope error on Mac using VS for Mac
Fix for "Error CS0136: A local or parameter named 'day' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter (CS0136) (FrontEnd)"